export { DAIClient, DAIError } from './client.js'
export {
  generateKeyPair,
  deriveAddressFromSigningKey,
  signData,
  createSigningProof,
  createRotationProof,
  buildTransfer,
  signTransaction,
  computeTxHash,
  pemToBytes,
  bytesToPem,
  computeJobPaymentHash,
  signJobPayment,
} from './signing.js'
export {
  seal,
  open,
  sealJSON,
  openJSON,
  isEnvelope,
  deriveEncryptionKeypair,
} from './chatcrypto.js'
export type { SealedEnvelope } from './chatcrypto.js'
export { DEFAULT_NODES, MAX_ATTACHMENT_BYTES } from './types.js'
export type {
  DAIClientOptions,
  NodeConfig,
  FetchFn,
  ScanOptions,
  ScanResult,
  BulkScanResult,
  JobStatus,
  JobStatusCode,
  ScanResultItem,
  BrainVerdict,
  BrainPollOptions,
  ScanWithVerdict,
  Method,
  PollOptions,
  AskOptions,
  AskJobRef,
  AskJobStatus,
  AskJobResult,
  ComputeOptions,
  ChatOptions,
  EstimateInput,
  EstimateResult,
  EstimateBreakdownItem,
  EstimateCall,
  FeeQuote,
  TokenRange,
  ChatResult,
  ChatAttachment,
  CascadeJobSummary,
  HfDatasetManifest,
  HfDatasetListResult,
  HfDatasetDownloadResult,
  McpServerStatus,
  McpStatusResult,
  NodeInfo,
  Skill,
  WalletBalance,
  AccountNonce,
  TxHistoryEntry,
  TxHistoryResult,
  DAITxRecord,
  TxSubmitResult,
  SendResult,
  PendingTxResult,
  RegisterKeyResult,
  MinerInfo,
} from './types.js'
export type { KeyPair, DAITx, JobPaymentParams } from './signing.js'
